server:
  port: 8081

spring:
  application:
    name: robot-management-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://robot-management-service-database:27017/robot_management}

    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}

  cache:
    type: redis

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:robot-management-service-kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  endpoint:
    health:
      show-details: always

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

    export:
      prometheus:
        enabled: true

topics:
  robot:
    created: ${SPRING_ROBOT_CREATED_TOPIC:robot.created}
    updated: ${SPRING_ROBOT_UPDATED_TOPIC:robot.updated}
    change-status: ${SPRING_ROBOT_CHANGE_STATUS_TOPIC:robot.change-status}
    deleted: ${SPRING_ROBOT_DELETED_TOPIC:robot.deleted}