server:
  port: 8081

spring:
  application:
    name: robot-management-service

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/robot-management-service}

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cache:
    type: redis

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  endpoint:
    health:
      show-details: always

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

    export:
      prometheus:
        enabled: true

topics:
  robot:
    created: ${ROBOT_CREATED_TOPIC:robot.created}
    updated: ${ROBOT_UPDATED_TOPIC:robot.updated}
    change-status: ${ROBOT_CHANGE_STATUS_TOPIC:robot.status.changed}
    deleted: ${ROBOT_DELETED_TOPIC:robot.deleted}